"""M5 — Microsoft GraphRAG (entity-relation graph baseline).

The eval plan's non-RAPTOR hierarchical baseline (evaluation_plan.pdf
section 3, system M5). GraphRAG builds an entity-relation graph with
community detection and summarisation — a different hierarchical
paradigm from RAPTOR's cluster tree (M4). M7 beating both M4 and M5 is
a stronger thesis result than beating M4 alone. M5 is a baseline to
beat, not an M7 component.

This is the BaseSystem wrapper. The graphrag 3.0.9 integration itself —
settings generation, bge-m3 injection, in-process indexing, local-search
retrieval — lives in src/graphrag_backend.py.

Design (per docs/M5_KICKOFF.md and evaluation_plan.pdf section 7):

  * Own corpus ingestion. GraphRAG ingests the corpus its own way; it
    does NOT reuse the shared RAPTOR substrate or the harness chunker.
    The corpus is parsed once by the shared Docling parser (walk_corpus)
    and handed to GraphRAG as plain text.
  * Own cache namespace — cache/M5/<hash>/, NOT cache/RAPTOR/. The cache
    directory doubles as the GraphRAG project directory (input/, output/,
    settings.yaml live inside it).
  * Embedder parity. M5 uses bge-m3, the same embedder as M2/M3/M4/M7,
    injected into GraphRAG via the library model registry — not
    GraphRAG's OpenAI default — so an M5-vs-others delta is not
    confounded by the embedding model.
  * Generator held constant. Answers are generated by Qwen2.5-3B-Instruct
    via the shared harness generator; GraphRAG's own map-reduce answer
    LLM is not used. M5 differs from the other systems only in retrieval
    and embedding.
  * Retrieval unit divergence. GraphRAG retrieves text units and
    community reports, not RAPTOR-style leaf chunks. retrieve() adapts
    those into the harness RetrievedChunk type; the unit-count
    divergence from chunk-based systems is expected and documented
    (evaluation_plan.pdf section 7).

Cache key folds in: parsing identity + corpus content hash + the M5
extras from graphrag_identity() (pinned graphrag version, settings hash
covering chunk size/overlap/models/vector dim, index LLM, community
level, retrieval mode). The harness ChunkingConfig is NOT in the key —
M5 does not use the harness chunker; GraphRAG's chunk parameters are
folded in via the settings hash instead.

Efficiency note: retrieve() rebuilds the local-search context (reloads
the parquet artifacts, reconnects LanceDB) per query. Negligible for the
smoke test; for the full eval grid this is a candidate for caching the
context builder across queries.
"""

from __future__ import annotations

from dataclasses import asdict
from pathlib import Path

from .. import paths
from ..cache import CacheDir, Manifest, compute_cache_key, corpus_content_hash
from ..chunking import Chunk
from ..config import (
    BASE_ANSWER_SYSTEM_PROMPT,
    DEFAULT_CONFIG,
    EMBEDDER_MODEL,
    HarnessConfig,
)
from ..graphrag_backend import (
    GraphRAGContextUnit,
    build_index,
    graphrag_identity,
    load_artifacts,
    local_search_context,
    write_input_documents,
    write_settings,
)
from ..models import generate
from ..parsing import walk_corpus
from .base import AnswerResult, BaseSystem, RetrievedChunk


M5_CACHE_NAMESPACE = "M5"

# Files that mark a complete GraphRAG index, relative to the cache /
# project directory. cdir.is_complete() also requires manifest.json.
REQUIRED_FILES = (
    "settings.yaml",
    "output/entities.parquet",
    "output/communities.parquet",
    "output/relationships.parquet",
    "output/community_reports.parquet",
    "output/text_units.parquet",
)


class GraphRAGSystem(BaseSystem):
    system_id = "M5"

    def __init__(self, config: HarnessConfig = DEFAULT_CONFIG) -> None:
        super().__init__(config)
        self._project_dir: Path | None = None
        self._index_stats: dict = {}

    # --- index ----------------------------------------------------------------

    def index(self, corpus_path: Path) -> None:
        m5 = self.config.m5
        corpus_path = Path(corpus_path)
        chash = corpus_content_hash(corpus_path)

        # chunking_config={} — M5 chunks via GraphRAG, not the harness
        # chunker; GraphRAG's chunk size/overlap are folded into the key
        # through graphrag_identity()'s settings hash. embedder_model and
        # parsing identity are folded by compute_cache_key as usual.
        ckey = compute_cache_key(
            chunking_config={},
            embedder_model=EMBEDDER_MODEL,
            corpus_hash=chash,
            extra=graphrag_identity(m5),
        )
        cdir = CacheDir(paths.cache_dir(), M5_CACHE_NAMESPACE, ckey)
        project_dir = cdir.path

        if cdir.is_complete(REQUIRED_FILES):
            print(f"[{self.system_id}] cache hit: {project_dir}")
            self._project_dir = project_dir
            self._index_stats = self._collect_stats(project_dir)
            self._indexed = True
            return

        print(
            f"[{self.system_id}] cache miss -> building GraphRAG index at "
            f"{project_dir}"
        )
        parsed = list(
            walk_corpus(corpus_path, min_chars=self.config.chunking.min_chars_per_doc)
        )
        if not parsed:
            raise RuntimeError(f"No parseable documents in {corpus_path}")
        docs = {d.doc_id: d.text for d in parsed}

        project_dir.mkdir(parents=True, exist_ok=True)
        write_settings(m5, project_dir)
        write_input_documents(docs, project_dir)
        results = build_index(m5, project_dir)
        print(
            f"[{self.system_id}] GraphRAG indexing finished: "
            f"{len(results)} workflows"
        )

        self._project_dir = project_dir
        self._index_stats = self._collect_stats(project_dir)
        Manifest(
            system_id=M5_CACHE_NAMESPACE,
            cache_key=ckey,
            chunking_config={},
            embedder_model=EMBEDDER_MODEL,
            corpus_hash=chash,
            # GraphRAG has no leaf chunks; n_text_units is the closest
            # analogue for the manifest's n_chunks field.
            n_chunks=int(self._index_stats.get("n_text_units", 0)),
            files=list(REQUIRED_FILES),
            extra={
                "m5": asdict(m5),
                "graphrag_identity": graphrag_identity(m5),
                "index_stats": self._index_stats,
            },
        ).save(cdir.manifest_path)

        self._indexed = True

    def _collect_stats(self, project_dir: Path) -> dict:
        """Counts from the GraphRAG parquet outputs.

        Doubles as cache-hit validation (the artifacts must load).
        n_community_reports > 0 confirms graph construction and community
        detection actually ran — the C4 smoke sanity check asserts this.
        """
        arts = load_artifacts(project_dir)
        return {
            "n_entities": int(len(arts.entities)),
            "n_communities": int(len(arts.communities)),
            "n_relationships": int(len(arts.relationships)),
            "n_community_reports": int(len(arts.community_reports)),
            "n_text_units": int(len(arts.text_units)),
        }

    @property
    def index_stats(self) -> dict:
        return dict(self._index_stats)

    # --- retrieve -------------------------------------------------------------

    @staticmethod
    def _unit_to_retrieved(unit: GraphRAGContextUnit, rank: int) -> RetrievedChunk:
        """Adapt a GraphRAG context unit into the harness RetrievedChunk.

        `graphrag_kind` is preserved in chunk metadata so answer() can
        keep text units (primary evidence) and community reports
        (orientation) distinct in the prompt.
        """
        chunk = Chunk(
            chunk_id=unit.unit_id,
            doc_id=unit.source or unit.kind,
            text=unit.text,
            n_words=len(unit.text.split()),
            position=rank,
            metadata={
                "graphrag_kind": unit.kind,
                "graphrag_source": unit.source,
            },
        )
        return RetrievedChunk(chunk=chunk, score=float(unit.score), rank=rank)

    def retrieve(self, query: str, k: int | None = None) -> list[RetrievedChunk]:
        self._require_indexed()
        assert self._project_dir is not None
        m5 = self.config.m5
        k = k or m5.top_k_final
        units = local_search_context(m5, self._project_dir, query, k=k)
        return [self._unit_to_retrieved(u, i) for i, u in enumerate(units)]

    # --- answer ---------------------------------------------------------------

    def answer(self, query: str, k: int | None = None) -> AnswerResult:
        self._require_indexed()
        t0 = self._now()
        retrieved = self.retrieve(query, k)

        # Local-search + community-orientation mode: community reports are
        # orientation context, text units are primary evidence. The prompt
        # keeps them distinct; the shared base answer prompt is unchanged
        # (generator held constant, evaluation_plan.pdf section 7).
        orientation = [
            r for r in retrieved
            if r.chunk.metadata.get("graphrag_kind") == "community_report"
        ]
        evidence = [
            r for r in retrieved
            if r.chunk.metadata.get("graphrag_kind") != "community_report"
        ]

        parts: list[str] = []
        if orientation:
            parts.append(
                "Orientation (GraphRAG community summaries):\n"
                + "\n".join(f"- {r.chunk.text}" for r in orientation)
            )
        evidence_block = "\n\n".join(
            f"[{i + 1}] {r.chunk.text}" for i, r in enumerate(evidence)
        )
        parts.append(f"Evidence:\n{evidence_block}")
        user_prompt = "\n\n".join(parts) + f"\n\nQuestion: {query}"

        ans = generate(
            system_prompt=BASE_ANSWER_SYSTEM_PROMPT,
            user_prompt=user_prompt,
            cfg=self.config.generation,
        )
        return AnswerResult(
            query=query,
            answer=ans,
            retrieved=retrieved,
            latency_s=self._now() - t0,
            n_retrieval_calls=1,
            extra={"index_stats": self.index_stats},
        )
